### ISSUE TITLE
你好，可以提供一下你的测试视频吗？谢谢

### ISSUE THREAD

**Issue by zqs1996** [MrP123456/Frame-difference-method#1]

**Comment by MrP123456** [comment]
您好。
由于保密的原因我无法将原视频放上去，但是网上任何运动检测的视频都是通用的。
目前还没有时间整理整个流程，在README中详细的描述算法流程。
如果您对我的项目感兴趣，我们可以进一步地交流讨论。

**Comment by zqs1996** [comment]
> 您好。 由于保密的原因我无法将原视频放上去，但是网上任何运动检测的视频都是通用的。 目前还没有时间整理整个流程，在README中详细的描述算法流程。 如果您对我的项目感兴趣，我们可以进一步地交流讨
